### ISSUE TITLE
Seems like you have an error with Bank leumi

### ISSUE THREAD

**Issue by rabbishuki** [soryy708/il-bank-account-validator#5]
https://github.com/soryy708/il-bank-account-validator/blob/cf7a9e550392af9944bd9410bd1f5923ef8fc358/index.js#L124-L139

If I understand correctly, your code should be:
Line 133: `sum += accountNumberDigits[6]; `
Line 134: `sum += accountNumberDigits[7]; `

**Comment by soryy708** [comment]
It looks like you have found something.
[Image from specification.pdf](https://user-images.githubusercontent.com/2157782/41816540-8ee6c4ec-7790-11e8-8515-50dc64102bfe.png)

**Comment by soryy708** [comment]
Here's a pull request: https://github.com/soryy708/il-bank-account-validator/pull/6
I don't have a Leumi bank account. Could you checkout the branch and test with yours? This will let me know if the fix was successful or not.

**Comment by soryy708** [comment]
Merged PR
